1 cup (130g) all purpose flour
1 cup (207g) sugar
6 tbsp (43g) unsweetened cocoa powder*
1 tsp baking soda
1/2 tsp salt
1 large egg
1/2 cup (120ml) buttermilk
1/2 cup (120ml) vegetable oil
3/4 tsp vanilla
1/2 cup (120ml) hot water*
CHOCOLATE FROSTING
1 1/4 cups (280g) unsalted butter, room temperature
12 oz semi sweet chocolate chips, melted
3 tbsp (22g) Hershey’s dark cocoa powder
5 cups (575g) powdered sugar
Pinch of salt
4–5 tbsp (60-75ml) heavy whipping cream